
# erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
speed_to_erpm_gain: 2100

# The state here is the VESC state reported on the topic /vesc/sensors/core. On echoing messages
# from this topic I realized that the state.speed is reported to be in the range of 37 to 140, for
# a stationary car. So I should probably set the value for speed_to_erpm_offset_ as
# (37+140)/2 = ~90
speed_to_erpm_offset: 91.0

tachometer_ticks_to_meters_gain: 0.00225
# servo smoother - limits rotation speed and smooths anything above limit
max_servo_speed: 3.2 # radians/second
servo_smoother_rate: 75.0 # messages/sec

# servo smoother - limits acceleration and smooths anything above limit
max_acceleration: 2.5 # meters/second^2
throttle_smoother_rate: 75.0 # messages/sec

# servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
steering_angle_to_servo_gain: -1.0
steering_angle_to_servo_offset: 0.5304

# publish odom to base link tf
vesc_to_odom/publish_tf: true

# car wheelbase is about 25cm 
wheelbase: .34

vesc_driver:
  port: /dev/sensors/vesc
  duty_cycle_min: 0.0
  duty_cycle_max: 0.0
  current_min: 0.0
  current_max: 20.0
  brake_min: -20000.0
  brake_max: 200000.0
  speed_min: -8000
  speed_max: 8000
  position_min: 0.0
  position_max: 0.0
  servo_min: 0.15
  servo_max: 0.85
